# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KalshiCli < Formula
  desc "CLI for the Kalshi prediction market exchange"
  homepage "https://github.com/6missedcalls/kalshi-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.1/kalshi-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "2a7259d5bf78b8b12bf91175b9e543b1fa2d8281cbeec7d0ee4e3451d25a10ba"

      def install
        bin.install "kalshi-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.1/kalshi-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "f5a6431eaa8124e583671472ea209c66e45221cc3a98e1470052a65f663b294d"

      def install
        bin.install "kalshi-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.1/kalshi-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "f6d81d6c1c25944a091af66c641fa2be846715bec8c749aef17142e363c676ee"
      def install
        bin.install "kalshi-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.1/kalshi-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "ac6eab81bd9b618356d4056d934f6bba20529becbcd7f9add1cfc4bcf7531407"
      def install
        bin.install "kalshi-cli"
      end
    end
  end

  test do
    system "#{bin}/kalshi-cli", "version"
  end
end
