# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KalshiCli < Formula
  desc "CLI for the Kalshi prediction market exchange"
  homepage "https://github.com/6missedcalls/kalshi-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.0/kalshi-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "8fc53afb40f56c14f19f9350b5d8fb95ac0cd1fb59b57be449e9cd2edf827d41"

      def install
        bin.install "kalshi-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.0/kalshi-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "6a5b60265fe0e71a4a4dcf306696aa3de0706283ebf7995aed972667f5f1aecc"

      def install
        bin.install "kalshi-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.0/kalshi-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "1c67240757e3629db4dcf15f242f87d58ed5c18ff8ee1bb97b80df0d737eead7"
      def install
        bin.install "kalshi-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/6missedcalls/kalshi-cli/releases/download/v0.1.0/kalshi-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "37b2daa78bcc299a25bdc44e2f086d88c96e265b909bd69082e20dfc037b6ade"
      def install
        bin.install "kalshi-cli"
      end
    end
  end

  test do
    system "#{bin}/kalshi-cli", "--help"
  end
end
